### ISSUE TITLE
AWS X-Ray. Container commend seems to be wrong.

### ISSUE THREAD

**Issue by kostyaplis** [okgolove/helm-charts#38]
Getting following error when installing x-ray daemon using the latest `aws-xray-3.1.0` chart.
Error:
```
Error: failed to start container "xray-daemon": Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "/usr/bin/xray": stat /usr/bin/xray: no such file or directory: unknown
```

Looking at chart [container command](https://github.com/okgolove/helm-charts/blob/05163419448a0d26e807238a8c6768976550e468/charts/aws-xray/templates/daemonset.yaml#L35) and [dockerfile entrypoint ](https://github.com/aws/aws-xray-daemon/blob/a17113f170524d3486690e3261b15506a5b44d4f/Dockerfile#L21) it is clear that those don't match.

It seems that there were no changes on filepath (dockerfile) nor command (chart). So I'm wondering how the chart supposed to work for anyone.

Can be fixed in couple ways:
Maybe we can make `command` configurable with current value as default in `values.yaml`(in case it works for someone with older image tags, so we can keep backward compatibility).
Or just update the command with  valid executable path.

Happy to provide a PR on that.

**Comment by okgolove** [comment]
@kostyaplis nice catch, thank you! Fixed in #39
