### ISSUE TITLE
Support for loadBalancerSourceRanges in Goldpinger

### ISSUE THREAD

**Issue by acarbonaro** [okgolove/helm-charts#81]
**FEATURE REQUEST**:

Please add support for `loadBalancerSourceRanges`.

**Comment by okgolove** [comment]
Hi @acarbonaro. What chart are you talking about?

**Comment by acarbonaro** [comment]
As per the Kubernetes docs `loadBalancerSourceRanges` limit which client IP's can access the Network Load Balancer.  My current use-case already leverages `loadBalancerSourceRanges` for Goldpinger, but I was hoping to switch to your helm chart.  Apologies for not providing more context here, I thought this issue was just for Goldpinger.

https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer
