### ISSUE TITLE
Error: template: goldpinger/templates/daemonset.yaml:65:53: executing "goldpinger/templates/daemonset.yaml" at <eq $k.value "true">: error calling eq: incompatible types for comparison.

### ISSUE THREAD

**Issue by ifelsefi** [okgolove/helm-charts#83]
Hi 

When using `extraEnv` I get a bug.  My key value pairs:

```extraEnv:
  - name: USE_HOST_IP
    value: true
  - name: POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
  - name: HOSTS_TO_RESOLVE
    value: "gitlab.domain.local"
  - name: TCP_TARGETS
    value: 10.69.24.235:6443 10.69.24.236:6443 10.69.24.233:6443 10.69.24.232:6443 10.69.24.231:6443
 ```
 
 
 The error is `Error: template: goldpinger/templates/daemonset.yaml:65:53: executing "goldpinger/templates/daemonset.yaml" at <eq $k.value "true">: error calling eq: incompatible types for comparison.`
 
 I am using helm v3.6.3 on a k8s 1.24.10 cluster.
 
 Thanks!

**Comment by okgolove** [comment]
Hi @ifelsefi!
Thank you for notifying.
Just use `"true"` (string) instead of `true` (bool).
